#!/bin/sh

sxhkd &

xrdb ~/.Xresources

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a vlc desktop='^3'

feh --bg-fill $BACKGROUND

"$HOME/.config/polybar/launch.sh"
